services:
  wc_solutions_postgres_db:
    image: postgres:15
    container_name: wc_solutions_db
    restart: unless-stopped
    env_file:
      - ~/envs/wosooly.env   # <- add this line
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wc_network

  wc_solutions_redis_backend:
    image: redis:7
    container_name: wc_solutions_redis_backend
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wc_network

  wc_solutions_fastapi_app:
    build: .
    container_name: wc_solutions_fastapi_app
    restart: unless-stopped
    env_file:
      - ~/envs/wosooly.env   # <- add this line
    command: >
      gunicorn main:app
      -w 4
      -k uvicorn.workers.UvicornWorker
      -b 0.0.0.0:8000
      --forwarded-allow-ips="*"
    depends_on:
      wc_solutions_postgres_db:
        condition: service_healthy
      wc_solutions_redis_backend:
        condition: service_healthy
    networks:
      - wc_network

  wc_solutions_celery_worker:
    build: .
    container_name: wc_solutions_celery_worker
    restart: unless-stopped
    env_file:
      - ~/envs/wosooly.env   # <- add this line
    command: ["sh", "/app/wait_and_start_celery.sh"]
    depends_on:
      wc_solutions_postgres_db:
        condition: service_healthy
      wc_solutions_redis_backend:
        condition: service_healthy
    networks:
      - wc_network

  wc_solutions_celery_beat:
    build: .
    container_name: wc_solutions_celery_beat
    restart: unless-stopped
    command: celery -A celery_app.celery beat --loglevel=info
    env_file:
      - ~/envs/wosooly.env   # <- add this line
    depends_on:
      wc_solutions_postgres_db:
        condition: service_healthy
      wc_solutions_redis_backend:
        condition: service_healthy
    networks:
      - wc_network

  wc_solutions_nginx:
    image: nginx:latest
    container_name: wc_solutions_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      
    depends_on:
      - wc_solutions_fastapi_app
    networks:
      - wc_network

  wc_solutions_certbot:
    image: certbot/certbot
    container_name: wc_solutions_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h & wait $${!};
      done"
    networks:
      - wc_network

volumes:
  pgdata:
    external: true
  redisdata:
    external: true

networks:
  wc_network:
    driver: bridge